[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = """        RENTAL = HEX('b18f43'),"""
position = "after"
payload = """DCKST_ORANGE = HEX("e67e22"),
DCKST_RED = HEX("ff746c"),
DCKST_DEEP_RED = HEX("8c1f19"),
DCKST_TEAL = HEX("6d888d"),
DCKST_PERI = HEX("ccccff"),
DCKST_NEONGREEN = HEX("78be20"),
DCKST_BLINDSIZE = HEX("34744d"),
DCKST_H_RED = HEX("BC002D"),
DCKST_NICO_GREEN = HEX("01B051"),
DCKST_HARMONIC_ORANGE = HEX("ff4707"),
DCKST_FELIMONIAL = HEX("aa55ff"),
DCKST_MAXEY_YELLOW = HEX("ffcf0e"),
DCKST_EXOPLANET_BLUE = HEX("1c4587"),
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  return G.ARGS.LOC_COLOURS[_c] or _default or G.C.UI.TEXT_DARK"""
position = "before"
payload = """G.ARGS.LOC_COLOURS.dckst_orange = G.C.DCKST_ORANGE
G.ARGS.LOC_COLOURS.dckst_red = G.C.DCKST_RED
G.ARGS.LOC_COLOURS.dckst_deep_red = G.C.DCKST_DEEP_RED
G.ARGS.LOC_COLOURS.dckst_teal = G.C.DCKST_TEAL
G.ARGS.LOC_COLOURS.dckst_peri = G.C.DCKST_PERI
G.ARGS.LOC_COLOURS.dckst_neongreen = G.C.DCKST_NEONGREEN
G.ARGS.LOC_COLOURS.dckst_blindsize = G.C.DCKST_BLINDSIZE
G.ARGS.LOC_COLOURS.dckst_h_red = G.C.DCKST_H_RED
G.ARGS.LOC_COLOURS.dckst_nico_green = G.C.DCKST_NICO_GREEN
G.ARGS.LOC_COLOURS.dckst_harmonic_orange = G.C.DCKST_HARMONIC_ORANGE
G.ARGS.LOC_COLOURS.dckst_felimonial = G.C.DCKST_FELIMONIAL
G.ARGS.LOC_COLOURS.dckst_maxey_yellow = G.C.DCKST_MAXEY_YELLOW
G.ARGS.LOC_COLOURS.dckst_exoplanet_blue = G.C.DCKST_EXOPLANET_BLUE
"""
overwrite = true
match_indent = true